-- Customer Behaviour Analysis: Key Business Questions and Insights

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT
	gender,
	SUM(purchase_amount) as revenue
FROM
	customer
GROUP BY
	gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT
	customer_id,
	age,
	age_group,
	gender,
	location,
	item_purchased,
	purchase_amount
FROM
	customer
WHERE
	discount_applied = 'Yes'
	AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer)
ORDER BY
	purchase_amount DESC;

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5
	item_purchased,
	ROUND(AVG(review_rating), 2) as avg_review_rating
FROM
	customer
GROUP BY
	item_purchased
ORDER BY
	avg_review_rating DESC;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT
	shipping_type,
	AVG(purchase_amount) as avg_purchase_amount
FROM
	customer
WHERE
	shipping_type IN ('Standard', 'Express')
GROUP BY
	shipping_type
ORDER BY
	avg_purchase_amount DESC;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT
	COUNT(customer_id) as customers,
	subscription_status,
	AVG(purchase_amount) as avg_purchase_amount,
	SUM(purchase_amount) as revenue
FROM
	customer
GROUP BY
	subscription_status
ORDER BY
	revenue DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5
	item_purchased,
	SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) discounted_purchase,
	COUNT(item_purchased) as total_purchases,
	SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(item_purchased) as discounted_rate
FROM
	customer
GROUP BY
	item_purchased
ORDER BY
	discounted_rate DESC;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
WITH customer_segments AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 
				THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 
				THEN 'Returning'
			WHEN previous_purchases > 10
				THEN 'Loyal'
            ELSE 
				'N/A'
        END AS customer_type
    FROM customer
)
SELECT
    customer_type,
    COUNT(*) AS segment_count
FROM 
	customer_segments
GROUP BY 
	customer_type
ORDER BY 
	segment_count DESC;

-- Q8. What are the top 3 most purchased products within each category? 
WITH category_purchase_count_ranking as
(
	SELECT
		category,
		item_purchased,
		COUNT(*) as purchase_count,
		ROW_NUMBER()
		OVER(PARTITION BY category ORDER BY COUNT(*) DESC) as rank_count
	FROM
		customer
	GROUP BY
		category,
		item_purchased
)
SELECT
	category,
	item_purchased,
	purchase_count
FROM
	category_purchase_count_ranking
WHERE
	rank_count <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
	subscription_status,
	COUNT(*) customer_count,
	ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM customer WHERE previous_purchases > 5), 2) as repeat_customer_pct
FROM
	customer
WHERE
	previous_purchases > 5
GROUP BY
	subscription_status
ORDER BY
	customer_count DESC;

-- Q10. What is the revenue contribution of each age group?
SELECT
	age_group,
	SUM(purchase_amount) as revenue,
	ROUND(SUM(purchase_amount) * 100.0 / (SELECT SUM(purchase_amount) FROM customer), 2) as revenue_pct
FROM
	customer
GROUP BY
	age_group
ORDER BY 
	revenue DESC;